spring:
  ai:
    openai:
      base-url: ${flower.ai.base-url}
      api-key: ${flower.ai.api-key}
      chat:
        options:
          model: ${flower.ai.chat.model}
  config:
    import: classpath:session.yml

system:
  chat:
    file: classpath:session.txt
    group: DEFAULT_GROUP
    timeout-ms: 20000

